DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS groceryStore CASCADE;
DROP TABLE IF EXISTS client CASCADE;
DROP TABLE IF EXISTS productClient CASCADE;


CREATE TABLE IF NOT EXISTS product
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    kcal INTEGER NOT NULL
    );

CREATE TABLE IF NOT EXISTS groceryStore
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS client
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    groceryStoreID BIGINT REFERENCES groceryStore (id)
    );

CREATE TABLE IF NOT EXISTS productClient
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    clientID BIGINT REFERENCES client (id),
    productID BIGINT REFERENCES product (id)
    );